#!/usr/bin/env bash
#configures ubuntu server's localhost and facebook.com
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i  '218.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
rm -f ~/hosts.new
